<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" xmlns:tns="http://my.org/schema/SIP/NotificationServiceInterface" xmlns:tns2="http://www.iir.com/sorna/NIEM/2.1/notification/1.0" xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsrm="http://schemas.xmlsoap.org/ws/2005/02/rm/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="NotificationServiceInterface" targetNamespace="http://my.org/schema/SIP/NotificationServiceInterface" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
      <xsd:import namespace="http://www.iir.com/sorna/NIEM/2.1/notification/1.0" schemaLocation="../.././schema/information/XMLschemas/exchange/RelNotice.xsd"/>
    </xsd:schema>
  </types>
  <message name="RelocationNoticeMessage">
    <part element="tns2:SORNARelocationNotice" name="RelocationNotice"/>
  </message>
  <portType name="RelocationNoticeInterface">
    <operation name="RelocationNotification">
      <input message="tns:RelocationNoticeMessage"/>
    </operation>
  </portType>
  <binding name="RelocationNoticeSOAPBindingSIRS-RelocationNotificationPortBinding" type="tns:RelocationNoticeInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaws:UsingAddressing xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" wsdl:required="true"/>
    <sp:PolicyReference URI="#wss-policy"/>
    <operation name="RelocationNotification">
      <soap:operation soapAction="http://my.org/schema/SIP/SIRS-Notification/RelocationNoticeSOAPBinding/RelocationNotification" style="document"/>
      <input>
        <soap:body use="literal"/>
        <sp:PolicyReference/>
      </input>
    </operation>
  </binding>
  <service name="SIRS-NotificationService">
    <port binding="tns:RelocationNoticeSOAPBindingSIRS-RelocationNotificationPortBinding" name="SIRS-RelocationNotificationPortPort">
      <soap:address location="No Target Adress"/>
    </port>
  </service>
</definitions>
