<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:CRSUB="http://it.ojp.gov/gist/200/Corrections/SubjectMessageTypes" xmlns:SAN="http://ijis.org/GRA/Annotations" xmlns:SANWSDL="http:/ijis.org/GRA/WSDLAnnotations" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" xmlns:template="http://gra.ijis.org/template" xmlns:tns="http://my.org/CorrectionsComponents/CaseFileSubscriber" xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsrm="http://schemas.xmlsoap.org/ws/2005/02/rm/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="CaseFileSubscriber" targetNamespace="http://my.org/CorrectionsComponents/CaseFileSubscriber" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <SANWSDL:WSDLServiceProvider wsu:Id="CaseFileSubscriber"/>
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
      <xsd:import namespace="http://it.ojp.gov/gist/200/Corrections/SubjectMessageTypes" schemaLocation="../.././XMLschemas/exchange/SubjectMessageModel.xsd"/>
    </xsd:schema>
  </types>
  <message name="SubjectInformationMessage">
    <part name="SubjectInformationMessage" type="CRSUB:SubjectInformationMessage"/>
  </message>
  <portType name="NotificationInterface">
    <operation name="Notify">
      <input message="tns:SubjectInformationMessage" name="SubjectNotification"/>
    </operation>
  </portType>
  <binding name="Usage_of_SubjectSubscriptionInterfaceSubscriberBinding" type="tns:NotificationInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaws:UsingAddressing xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" wsdl:required="true"/>
    <operation name="Notify">
      <soap:operation soapAction="http://my.org/CorrectionsInterfaces/NotificationInterface/Notify" style="document"/>
      <input name="SubjectNotification">
        <soap:body parts="request" use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="CaseFileSubscriberService">
    <port binding="tns:Usage_of_SubjectSubscriptionInterfaceSubscriberBinding" name="SubscriberPort">
      <soap:address/>
    </port>
  </service>
</definitions>
