<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
					xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
					xmlns:xsd="http://www.w3.org/2001/XMLSchema"
					xmlns:_arg_wsdlPrefix_="_arg_wsdlNamespace_"  
					targetNamespace="_arg_wsdlNamespace_"> 

</wsdl:definitions>