/**
 */
package data.grauml.graAnnotationModel;

import org.eclipse.emf.common.util.EList;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Participant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * Each Participant represents an ExchangePartner of the ServiceDescription. Participant annotations are generated by phase-1 provisioning.  A Participant may be modeled directly realizing an Actor in the logical model, in which case a single Participant corresponding to that Actor is generated. A Participant may be modeled realizing a Package in the logical model, in which case a Participant is generated corresponding to every Actor in the package.  A Participant is also generated for every Actor that plays a role in any Interaction owned by the Collaboration realized by the ServiceDescription.  If Actors are related in the logical model by inheritance, then a Participant generated from a specializing Actor will contain a generalization element that identifies the Participant corresponding to the generalizing Actor.
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link data.grauml.graAnnotationModel.Participant#getParticipatingOrganization <em>Participating Organization</em>}</li>
 *   <li>{@link data.grauml.graAnnotationModel.Participant#getGeneralization <em>Generalization</em>}</li>
 * </ul>
 * </p>
 *
 * @see data.grauml.graAnnotationModel.GraAnnotationModelPackage#getParticipant()
 * @model
 * @generated
 */
public interface Participant extends GraServiceAnnotationBase {
	/**
	 * Returns the value of the '<em><b>Participating Organization</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Participating Organization</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * An organization acting as a participant.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Participating Organization</em>' containment reference.
	 * @see #setParticipatingOrganization(Organization)
	 * @see data.grauml.graAnnotationModel.GraAnnotationModelPackage#getParticipant_ParticipatingOrganization()
	 * @model containment="true" ordered="false"
	 * @generated
	 */
	Organization getParticipatingOrganization();

	/**
	 * Sets the value of the '{@link data.grauml.graAnnotationModel.Participant#getParticipatingOrganization <em>Participating Organization</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Participating Organization</em>' containment reference.
	 * @see #getParticipatingOrganization()
	 * @generated
	 */
	void setParticipatingOrganization(Organization value);

	/**
	 * Returns the value of the '<em><b>Generalization</b></em>' containment reference list.
	 * The list contents are of type {@link data.grauml.graAnnotationModel.Participant}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Generalization</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * Represents the fact that this Participant is a "kind of" the generalizing Participant. Derived from Actor generalization.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Generalization</em>' containment reference list.
	 * @see data.grauml.graAnnotationModel.GraAnnotationModelPackage#getParticipant_Generalization()
	 * @model containment="true" ordered="false"
	 * @generated
	 */
	EList<Participant> getGeneralization();

} // Participant
