<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" xmlns:tns="http://my.org/schema/SIP_WS_1.3/OTNS" xmlns:tns2="http://usdoj.gov/leisp/lexs/publishdiscover/3.1" xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsrm="http://schemas.xmlsoap.org/ws/2005/02/rm/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="OTNS" targetNamespace="http://my.org/schema/SIP_WS_1.3/OTNS" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
      <xsd:import namespace="http://usdoj.gov/leisp/lexs/publishdiscover/3.1" schemaLocation="../.././schema/information/Compact_Offender_Profile/LEXS3.1.4/xsd/publish-discover/3.1/publish-discover.xsd"/>
    </xsd:schema>
  </types>
  <message name="OffenderTransferNotificationMessage">
    <part element="tns2:doPublish" name="OffenderTransferNotificationMessage"/>
  </message>
  <portType name="OffenderTransferNotificationService">
    <operation name="NotifyofOffenderTransfer">
      <input message="tns:OffenderTransferNotificationMessage" name="OffenderTransferNotificationMessage"/>
    </operation>
  </portType>
  <binding name="OffenderTransferNotificationServiceSOAPBindingOffenderTransferNotificationServiceBinding" type="tns:OffenderTransferNotificationService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaws:UsingAddressing/>
    <operation name="NotifyofOffenderTransfer">
      <soap:operation soapAction="http://my.org/schema/SIP_WS_1.3/OffenderTransferNotificationServiceService/OffenderTransferNotificationService/NotifyofOffenderTransfer" style="document"/>
      <input name="OffenderTransferNotificationMessage"/>
    </operation>
  </binding>
  <service name="OffenderTransferNotificationServiceServiceService">
    <port binding="tns:OffenderTransferNotificationServiceSOAPBindingOffenderTransferNotificationServiceBinding" name="OffenderTransferNotificationServicePort">
      <soap:address location="http://localhost"/>
    </port>
  </service>
</definitions>
