<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" xmlns:tns="http://my.org/schema/SIP_WS_1.3/OTNS_Policy" xmlns:wsaws="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsrm="http://schemas.xmlsoap.org/ws/2005/02/rm/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="OTNS_Policy" targetNamespace="http://my.org/schema/SIP_WS_1.3/OTNS_Policy" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="wss-policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <AsymmetricBinding xmlns="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
          <wsp:Policy>
            <wsp:ExactlyOne>
              <wsp:All>
                <OnlySignEntireHeadersAndBody/>
                <Layout>
                  <wsp:Policy>
                    <wsp:ExactlyOne>
                      <wsp:All>
                        <Strict/>
                      </wsp:All>
                    </wsp:ExactlyOne>
                  </wsp:Policy>
                </Layout>
                <IncludeTimestamp/>
                <InitiatorToken>
                  <wsp:Policy>
                    <wsp:ExactlyOne>
                      <wsp:All>
                        <X509Token xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                          <wsp:Policy>
                            <wsp:ExactlyOne>
                              <wsp:All>
                                <WssX509V3Token10/>
                                <RequireIssuerSerialReference/>
                              </wsp:All>
                            </wsp:ExactlyOne>
                          </wsp:Policy>
                        </X509Token>
                      </wsp:All>
                    </wsp:ExactlyOne>
                  </wsp:Policy>
                </InitiatorToken>
                <AlgorithmSuite>
                  <wsp:Policy>
                    <wsp:ExactlyOne>
                      <wsp:All>
                        <Basic256Sha256/>
                      </wsp:All>
                    </wsp:ExactlyOne>
                  </wsp:Policy>
                </AlgorithmSuite>
                <RecipientToken>
                  <wsp:Policy>
                    <wsp:ExactlyOne>
                      <wsp:All>
                        <X509Token xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                          <wsp:Policy>
                            <wsp:ExactlyOne>
                              <wsp:All>
                                <WssX509V3Token10/>
                                <RequireIssuerSerialReference/>
                              </wsp:All>
                            </wsp:ExactlyOne>
                          </wsp:Policy>
                        </X509Token>
                      </wsp:All>
                    </wsp:ExactlyOne>
                  </wsp:Policy>
                </RecipientToken>
              </wsp:All>
            </wsp:ExactlyOne>
          </wsp:Policy>
        </AsymmetricBinding>
        <Wss10 xmlns="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
          <wsp:Policy>
            <wsp:ExactlyOne>
              <wsp:All>
                <MustSupportRefIssuerSerial/>
              </wsp:All>
            </wsp:ExactlyOne>
          </wsp:Policy>
        </Wss10>
        <SignedParts xmlns="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
          <Header xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" sp:Name="To" sp:Namespace="http://www.w3.org/2005/08/addressing"/>
          <Header xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" sp:Name="ReplyTo" sp:Namespace="http://www.w3.org/2005/08/addressing"/>
          <Header xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" sp:Name="MessageID" sp:Namespace="http://www.w3.org/2005/08/addressing"/>
          <Header xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" sp:Name="Action" sp:Namespace="http://www.w3.org/2005/08/addressing"/>
          <Body/>
        </SignedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
</definitions>
